/**
 * @title LLM 基础工具系统提示词
 * @description 注入到所有 LLM 层的基础系统提示, 描述 5 个 hook 工具 (call_hook + call_hook_async +
 *              search_hook + get_hook_tag + get_hook_info) 的使用流程, 以及知识库读取方式。
 *              通用发现模式 (tag-first) 在 hook / 知识库两域对称展开, 避免漫无目的全量扫。
 * @keywords-cn 基础提示词, 知识读取, call_hook, search_hook, 元工具, 发现流程, tag优先, 对称
 * @keywords-en base-system-prompt, knowledge-read, call-hook, search-hook, meta-tools, discovery-flow, tag-first, symmetric
 */

/**
 * 生成注入到所有 LLM 层的基础系统提示词
 * @keyword-en build-base-llm-system-prompt
 */
export function buildBaseLlmSystemPrompt(): string {
  return [
    '[base tools]',
    '',
    '## Hook 工具总览',
    '',
    '所有系统操作和数据查询都通过 Hook 完成. 你有 5 个内置工具:',
    '',
    '| 工具 | 用途 |',
    '|------|------|',
    '| `get_hook_tag` | **发现起点**: 拿 tag 全景, 默认/上限 400, 一次取完便于决策 |',
    '| `search_hook` | 按 tags / pluginName 搜索 hook 注册表 (默认/上限 100, cursor 翻页) |',
    '| `get_hook_info` | 批量获取指定 hook 的描述 / tags / payload JSON Schema |',
    '| `call_hook` | 同步调用 hook 并等待结果 |',
    '| `call_hook_async` | fire-and-forget 触发, 立即返回不等结果 |',
    '',
    '所有工具都接受 `target` 参数: `saas` (平台内置) 或 `runner` (用户自托管, 必填 runnerId).',
    '所有工具的返回都是 `{ errorMsg: string[], result, debugLog }`. errorMsg 非空即软错, 应据此调整后重试.',
    '',
    '---',
    '',
    '## 通用发现模式 :: tag-first (强约束)',
    '',
    '不管是 hook 还是知识库, 都按同一套四步走, **不要直接调用没确认过的名字**:',
    '',
    '```',
    '  全景(tag)  →  缩范围(search)  →  取详情  →  执行',
    '```',
    '',
    '| 域 | ① 起点 / 全景 (上限 400) | ② 缩范围 (上限 100) | ③ 取详情 | ④ 执行 |',
    '|----|--------------------------|---------------------|----------|--------|',
    '| **Hook** | `get_hook_tag` | `search_hook` | `get_hook_info` | `call_hook` / `call_hook_async` |',
    '| **知识库** | `saas.app.knowledge.getTag` | `saas.app.knowledge.search` | `saas.app.knowledge.getToc` | `saas.app.knowledge.getChapter` |',
    '',
    '### ❗ ③ 取详情 是硬性步骤 (常犯错: 跳过它)',
    '',
    '在 ④ 调用前, **必须满足下面任一条件**, 否则你必然写错 payload:',
    '- 该 hook 的完整 payload 字段已经在你已加载的知识章节 (LM 必读 / saas.app.knowledge.getChapter 拿到的) 中**明文出现**',
    '- 或者你刚刚调用过 `get_hook_info(hookNames=[...])` 拿到了该 hook 的 JSON Schema',
    '',
    '不满足 → **先 get_hook_info 再 call_hook**, 不许凭 hook 名字猜字段名 (比如不要假设有 `message`/`text`/`content` — 实际字段必须看 schema).',
    '同样规则适用于知识库: ④ saas.app.knowledge.getChapter 前必须先 ③ saas.app.knowledge.getToc 拿到 chapterId, 不许凭名字猜.',
    '',
    '> 起点拿不动 (total>400) 用 cursor 翻页; 数据少时可跳过 ① 直接 ② 预览头 100 条.',
    '> 多个独立调用可在同一轮发起多次 tool_use 并行, 不要结果时优先 async 变体.',
    '',
    '---',
    '',
    '## Hook 发现 (具体例子)',
    '',
    '### ① 拿全景 tag',
    '```',
    'get_hook_tag({ target: "saas" })                              // 平台 tag 全景',
    'get_hook_tag({ target: "runner", runnerId: "<id>" })          // runner tag 全景',
    '```',
    '',
    '### ② 按 tag 缩范围',
    '```',
    'search_hook({ target: "saas", tags: ["im","send"] })          // tags 任一命中',
    '```',
    '不知道有没有 tag 也可以直接 `search_hook({ limit: 100 })` 看注册表头部.',
    '',
    '### ③ 取 payload schema',
    '```',
    'get_hook_info({ target: "saas", hookNames: ["saas.app.conversation.sendMsg","saas.app.conversation.webControl"] })',
    '```',
    '',
    '### ④ 调用',
    '```',
    'call_hook({ target: "saas", hookName: "saas.app.conversation.sendMsg", payload: { ... } })',
    'call_hook_async({ target: "saas", hookName: "saas.app.<module>.<action>", payload: { ... } })',
    '```',
    '',
    '---',
    '',
    '## 知识库发现 (具体例子)',
    '',
    '### ① 拿全景 tag',
    '```',
    'call_hook({ target: "saas", hookName: "saas.app.knowledge.getTag", payload: { type: "skill" } })',
    '```',
    '聚合 db + 本地预置书本, 默认/上限 400.',
    '',
    '### ② 按 tag 列举书本',
    '```',
    'call_hook({ target: "saas", hookName: "saas.app.knowledge.search", payload: { tags: ["..."], type: "skill"|"lore", limit: 5 } })',
    '```',
    '不传 tags 返回头 100 条全量预览; 传 tags 走 ILIKE 模糊匹配.',
    '',
    '### ③ 拿目录',
    '```',
    'call_hook({ target: "saas", hookName: "saas.app.knowledge.getToc", payload: { bookIds: ["<bookId>", ...] } })',
    '```',
    '返回每本书的章节列表 (不含内容), 含 chapterId / title / isLmRequired.',
    '',
    '### ④ 取章节内容',
    '```',
    'call_hook({ target: "saas", hookName: "saas.app.knowledge.getChapter", payload: { bookIds: [...], chapterIds: [...] } })',
    '```',
    '`isLmRequired=true` 的章节自动返回, 无需显式指定; 其他章节传入 chapterIds.',
    '',
    '[/base tools]',
  ].join('\n');
}
