/**
 * @title LLM 基础工具系统提示词
 * @description 注入到所有 LLM 层的基础系统提示, 描述 5 个 hook 工具 (call_hook + call_hook_async +
 *              search_hook + get_hook_tag + get_hook_info) 的使用流程, 以及知识库读取方式。
 * @keywords-cn 基础提示词, 知识读取, call_hook, search_hook, 元工具, 发现流程
 * @keywords-en base-system-prompt, knowledge-read, call-hook, search-hook, meta-tools, discovery-flow
 */

/**
 * 生成注入到所有 LLM 层的基础系统提示词
 * @keyword-en build-base-llm-system-prompt
 */
export function buildBaseLlmSystemPrompt(): string {
  return [
    '[base tools]',
    '',
    '## Hook 工具总览',
    '',
    '所有系统操作和数据查询都通过 Hook 完成. 你有 5 个内置工具:',
    '',
    '| 工具 | 用途 |',
    '|------|------|',
    '| `search_hook` | 按 tags / pluginName 搜索 hook 注册表 (默认 100 条, 支持 cursor 翻页) |',
    '| `get_hook_tag` | 获取 hook 的 tag 频次榜, 用于先看类目再缩范围 |',
    '| `get_hook_info` | 批量获取指定 hook 的描述 / tags / payload JSON Schema |',
    '| `call_hook` | 同步调用 hook 并等待结果 |',
    '| `call_hook_async` | fire-and-forget 触发, 立即返回不等结果 |',
    '',
    '所有工具都接受 `target` 参数: `saas` (平台内置) 或 `runner` (用户自托管, 必填 runnerId).',
    '所有工具的返回都是 `{ errorMsg: string[], result, debugLog }`. errorMsg 非空即软错, 应据此调整后重试.',
    '',
    '---',
    '',
    '## Hook 发现流程 (重要)',
    '',
    '调用一个不熟悉的 hook 前, 强烈建议按以下顺序确认:',
    '',
    '1. **不知道 hook 名时** → 用 `search_hook` 按 tags / pluginName 缩小范围',
    '   ```',
    '   search_hook({ target: "runner", runnerId: "<id>", tags: ["im"] })',
    '   ```',
    '',
    '2. **看 tag 全景** → 用 `get_hook_tag` 列出当前端注册的所有 tag',
    '   ```',
    '   get_hook_tag({ target: "saas" })',
    '   ```',
    '',
    '3. **拿到候选 hook 后** → 用 `get_hook_info` 批量获取描述 + payload schema',
    '   ```',
    '   get_hook_info({ target: "saas", hookNames: ["send_msg", "web_control"] })',
    '   ```',
    '',
    '4. **确认参数后** → 用 `call_hook` (要结果) 或 `call_hook_async` (不要结果) 执行',
    '   ```',
    '   call_hook({ target: "saas", hookName: "send_msg", payload: { ... } })',
    '   ```',
    '',
    '> 多个独立调用可在同一轮回复中并行发起多次 tool_use, 不需要批量包装.',
    '> 不需要结果时优先 `call_hook_async`, 节省一次往返.',
    '',
    '---',
    '',
    '## 知识库读取',
    '',
    '知识库通过普通 hook 访问, 先查目录再按需读取章节:',
    '',
    '### 1. 获取目录',
    '```',
    'call_hook({ target: "saas", hookName: "get_knowledge_toc", payload: { bookIds: ["<bookId>", ...] } })',
    '```',
    '返回每本书的章节列表 (不含内容), 含 chapterId / title / isLmRequired.',
    '',
    '### 2. 获取章节内容',
    '```',
    'call_hook({ target: "saas", hookName: "get_knowledge_chapter", payload: { bookIds: [...], chapterIds: [...] } })',
    '```',
    '`isLmRequired=true` 的章节会自动返回, 无需显式指定; 其他章节传入 chapterIds.',
    '',
    '### 3. 按 tag 列举书本',
    '```',
    'call_hook({ target: "saas", hookName: "search_knowledge", payload: { tags: ["..."], type: "skill"|"lore", limit: 5 } })',
    '```',
    '不知道 bookId 时先用此 hook 定位书本, 再读取内容.',
    '',
    '[/base tools]',
  ].join('\n');
}
