/**
 * @title API Module Description
 * @description Description and keyword mapping for the API module.
 */

export const moduleDescription = {
  name: 'api',
  description: 'Centralized API definitions and endpoints for the application.',
  keywords: {
    'resource-api': {
      cn: '资源API',
      en: 'Resource API',
      file: 'resource.ts',
      functions: {
        upload: 'upload',
      },
      hashes: {
        upload: 'api_res_upload_001',
      },
    },
    'im-api': {
      cn: 'IM API',
      en: 'IM API',
      file: 'im.ts',
      functions: {
        createSession: 'createSession',
        updateSession: 'updateSession',
        getSessions: 'getSessions',
        getSession: 'getSession',
        deleteSession: 'deleteSession',
        getMembers: 'getMembers',
        addMember: 'addMember',
        inviteMembers: 'inviteMembers',
        removeMember: 'removeMember',
        getMessages: 'getMessages',
        hasNew: 'hasNew',
        sendMessage: 'sendMessage',
      },
      hashes: {
        inviteMembers: 'api_im_invite_members_001',
      },
    },
    'agent-api': {
      cn: '代理API',
      en: 'Agent API',
      file: 'agent.ts',
      functions: {
        getGroupHistory: 'getGroupHistory',
        sendMessage: 'sendMessage',
        getGroupList: 'getGroupList',
        getGroupDetail: 'getGroupDetail',
        createGroup: 'createGroup',
        updateGroup: 'updateGroup',
        deleteGroup: 'deleteGroup',
        getGroupSummaries: 'getGroupSummaries',
        listCheckpoints: 'listCheckpoints',
        getCheckpointDetail: 'getCheckpointDetail',
        getWorkflow: 'getWorkflow',
      },
    },
    'todo-api': {
      cn: '待办API',
      en: 'Todo API',
      file: 'todo.ts',
      functions: {
        list: 'list',
        get: 'get',
        create: 'create',
        update: 'update',
        delete: 'delete',
      },
    },
    'identity-api': {
      cn: '身份API',
      en: 'Identity API',
      file: 'agent.ts',
      functions: {
        listPrincipals: 'listPrincipals',
        listUsers: 'listUsers',
        createPrincipal: 'createPrincipal',
        updatePrincipal: 'updatePrincipal',
        deletePrincipal: 'deletePrincipal',
        listOrganizations: 'listOrganizations',
        createOrganization: 'createOrganization',
        updateOrganization: 'updateOrganization',
        deleteOrganization: 'deleteOrganization',
        listRoles: 'listRoles',
        createRole: 'createRole',
        updateRole: 'updateRole',
        deleteRole: 'deleteRole',
        listRolePermissions: 'listRolePermissions',
        upsertRolePermissions: 'upsertRolePermissions',
        listPermissionDefinitions: 'listPermissionDefinitions',
        createPermissionDefinition: 'createPermissionDefinition',
        deletePermissionDefinition: 'deletePermissionDefinition',
        listMemberships: 'listMemberships',
        addMembership: 'addMembership',
        removeMembership: 'removeMembership',
      },
      hashes: {
        listPrincipals: 'api_id_list_principals_001',
        listUsers: 'api_id_list_users_001a',
        createPrincipal: 'api_id_create_principal_002',
        updatePrincipal: 'api_id_update_principal_003',
        deletePrincipal: 'api_id_delete_principal_004',
        listOrganizations: 'api_id_list_orgs_005',
        createOrganization: 'api_id_create_org_006',
        updateOrganization: 'api_id_update_org_007',
        deleteOrganization: 'api_id_delete_org_008',
        listRoles: 'api_id_list_roles_009',
        createRole: 'api_id_create_role_010',
        updateRole: 'api_id_update_role_011',
        deleteRole: 'api_id_delete_role_012',
        listRolePermissions: 'api_id_list_role_perms_013',
        upsertRolePermissions: 'api_id_upsert_role_perms_014',
        listPermissionDefinitions: 'api_id_list_perm_defs_015',
        createPermissionDefinition: 'api_id_create_perm_def_016',
        deletePermissionDefinition: 'api_id_delete_perm_def_017',
        listMemberships: 'api_id_list_memberships_018',
        addMembership: 'api_id_add_membership_019',
        removeMembership: 'api_id_remove_membership_020',
      },
    },
  },
};
