/**
 * @title Agent Module Tip
 * @description Description and mapping for the Agent module.
 * @keywords-cn 模块描述, 关键词映射, 哈希对照
 * @keywords-en module-description, keyword-mapping, hash-map
 */

export const moduleTip = {
  description:
    'The Agent module provides the main workspace for the AI agent, including chat, workflow visualization, and quick access tools.',
  keywords: {
    cn: {
      代理列表hook: 'src/modules/agent/hooks/useAgents.ts',
      快捷项hook: 'src/modules/agent/hooks/useAgentQuickItems.ts',
      工作流类型: 'src/modules/agent/types/agent.types.ts',
      聊天面板: 'src/modules/agent/components/ChatPanel.vue',
      会话记录页面: 'src/modules/agent/pages/chat-panel/ChatSessionsPage.vue',
      会话内聊天记录页面:
        'src/modules/agent/pages/chat-panel/ChatMessagesPage.vue',
      通讯录页面: 'src/modules/agent/pages/chat-panel/ChatContactsPage.vue',
      日报页面: 'src/modules/agent/pages/chat-panel/ChatDailyPage.vue',
      会话hook: 'src/modules/agent/hooks/useAgentThreads.ts',
      检查点hook: 'src/modules/agent/hooks/useAgentCheckpoints.ts',
      创建会话: 'src/api/agent.ts',
      更新会话: 'src/api/agent.ts',
      聊天标签页: 'src/modules/agent/components/ChatPanel.vue',
      聊天会话列表组件: 'src/modules/agent/components/chat/ChatThreadList.vue',
      消息列表组件: 'src/modules/agent/components/chat/ChatMessageList.vue',
      聊天主页头部组件: 'src/modules/agent/components/chat/ChatHomeHeader.vue',
      对话窗口头部组件:
        'src/modules/agent/components/chat/ChatSessionHeader.vue',
      通讯录标签页: 'src/modules/agent/components/chat/ChatContactsPanel.vue',
      通讯录面板组件: 'src/modules/agent/components/chat/ChatContactsPanel.vue',
      通讯录排序: 'src/modules/agent/components/chat/ChatContactsPanel.vue',
      通讯录头像组件: 'src/modules/agent/components/chat/ChatContactAvatar.vue',
      通讯录标题组件: 'src/modules/agent/components/chat/ChatContactTitle.vue',
      通讯录数据hook: 'src/modules/agent/hooks/useChatContacts.ts',
      日报标签页: 'src/modules/agent/components/chat/ChatDailyPanel.vue',
      日报面板组件: 'src/modules/agent/components/chat/ChatDailyPanel.vue',
      输入区: 'src/modules/agent/components/chat/InputArea.vue',
      待办状态切换: 'src/modules/agent/components/ChatPanel.vue',
      侧边栏: 'src/modules/agent/components/Sidebar.vue',
      右侧面板: 'src/modules/agent/components/RightPanel.vue',
      右侧面板Tab注册表: 'src/modules/agent/config/tab.registry.ts',
      工作区: 'src/modules/agent/components/AgentWorkspace.vue',
      可关闭选项卡: 'src/modules/agent/components/RightPanel.vue',
      国际化: 'src/modules/agent/composables/useI18n.ts',
      语言弹窗: 'src/modules/agent/components/LanguageModal.vue',
      日期选择弹窗: 'src/modules/agent/components/DatePickerModal.vue',
      更多菜单: 'src/modules/agent/components/MorePanel.vue',
      移动端适配: 'src/modules/agent/components/AgentWorkspace.vue',
      仪表盘: 'src/modules/agent/components/RightPanel.vue',
      工作流监控弹窗: 'src/modules/agent/components/WorkflowMonitorModal.vue',
      工作流图组件: 'src/modules/agent/components/WorkflowDiagram.vue',
      状态管理: 'src/modules/agent/store/agent.store.ts',
      面板状态: 'src/modules/agent/store/panel.store.ts',
      右侧面板状态: 'src/modules/agent/store/right-panel.store.ts',
      聊天详情: 'src/modules/agent/components/ChatDetail.vue',
      会话切换弹窗: 'src/modules/agent/components/SessionSwitchModal.vue',
      代理枚举: 'src/modules/agent/enums/agent.enums.ts',
      代理实体: 'src/modules/agent/entities/agent.entity.ts',
      代理缓存: 'src/modules/agent/cache/agent.cache.ts',
      聊天历史缓存: 'src/modules/agent/cache/chat-history.cache.ts',
      IM配置缓存: 'src/modules/agent/cache/im-config.cache.ts',
      艾特建议: 'src/modules/agent/components/chat/InputArea.vue',
      常量: 'src/modules/agent/constants/agent.constants.ts',
      聊天hook: 'src/modules/agent/hooks/useAgentChat.ts',
      分组hook: 'src/modules/agent/hooks/useAgentGroups.ts',
      代理API适配: 'src/api/agent.ts',
      表情选择: 'src/modules/agent/components/chat/InputArea.vue',
      语音录制: 'src/modules/agent/components/chat/InputArea.vue',
      图片预览: 'src/modules/agent/components/chat/ChatMessageList.vue',
    },
    en: {
      agents_hook: 'src/modules/agent/hooks/useAgents.ts',
      quick_items_hook: 'src/modules/agent/hooks/useAgentQuickItems.ts',
      workflow_types: 'src/modules/agent/types/agent.types.ts',
      chat_panel: 'src/modules/agent/components/ChatPanel.vue',
      chat_sessions_page:
        'src/modules/agent/pages/chat-panel/ChatSessionsPage.vue',
      chat_messages_page:
        'src/modules/agent/pages/chat-panel/ChatMessagesPage.vue',
      chat_contacts_page:
        'src/modules/agent/pages/chat-panel/ChatContactsPage.vue',
      chat_daily_page: 'src/modules/agent/pages/chat-panel/ChatDailyPage.vue',
      chat_thread_list: 'src/modules/agent/components/chat/ChatThreadList.vue',
      chat_message_list:
        'src/modules/agent/components/chat/ChatMessageList.vue',
      chat_home_header: 'src/modules/agent/components/chat/ChatHomeHeader.vue',
      chat_session_header:
        'src/modules/agent/components/chat/ChatSessionHeader.vue',
      chat_contacts_panel:
        'src/modules/agent/components/chat/ChatContactsPanel.vue',
      contacts_sorting:
        'src/modules/agent/components/chat/ChatContactsPanel.vue',
      chat_contact_avatar:
        'src/modules/agent/components/chat/ChatContactAvatar.vue',
      chat_contact_title:
        'src/modules/agent/components/chat/ChatContactTitle.vue',
      chat_contacts_hook: 'src/modules/agent/hooks/useChatContacts.ts',
      chat_daily_panel: 'src/modules/agent/components/chat/ChatDailyPanel.vue',
      session_list: 'src/modules/agent/hooks/useAgentThreads.ts',
      create_session: 'src/api/agent.ts',
      update_session: 'src/api/agent.ts',
      sidebar: 'src/modules/agent/components/Sidebar.vue',
      right_panel: 'src/modules/agent/components/RightPanel.vue',
      tab_registry: 'src/modules/agent/config/tab.registry.ts',
      workspace: 'src/modules/agent/components/AgentWorkspace.vue',
      closeable_tabs: 'src/modules/agent/components/RightPanel.vue',
      i18n: 'src/modules/agent/composables/useI18n.ts',
      language_modal: 'src/modules/agent/components/LanguageModal.vue',
      date_picker_modal: 'src/modules/agent/components/DatePickerModal.vue',
      more_menu: 'src/modules/agent/components/MorePanel.vue',
      mobile_responsive: 'src/modules/agent/components/AgentWorkspace.vue',
      dashboard: 'src/modules/agent/components/RightPanel.vue',
      workflow_monitor_modal:
        'src/modules/agent/components/WorkflowMonitorModal.vue',
      workflow_diagram_component:
        'src/modules/agent/components/WorkflowDiagram.vue',
      state_management: 'src/modules/agent/store/agent.store.ts',
      panel_state: 'src/modules/agent/store/panel.store.ts',
      right_panel_store: 'src/modules/agent/store/right-panel.store.ts',
      chat_detail: 'src/modules/agent/components/ChatDetail.vue',
      session_switch_modal:
        'src/modules/agent/components/SessionSwitchModal.vue',
      input_area: 'src/modules/agent/components/chat/InputArea.vue',
      agent_enums: 'src/modules/agent/enums/agent.enums.ts',
      agent_entities: 'src/modules/agent/entities/agent.entity.ts',
      agent_cache: 'src/modules/agent/cache/agent.cache.ts',
      chat_history_cache: 'src/modules/agent/cache/chat-history.cache.ts',
      im_config_cache: 'src/modules/agent/cache/im-config.cache.ts',
      mentions_suggestions: 'src/modules/agent/components/chat/InputArea.vue',
      constants: 'src/modules/agent/constants/agent.constants.ts',
      chat_hook: 'src/modules/agent/hooks/useAgentChat.ts',
      sessions_hook: 'src/modules/agent/hooks/useAgentThreads.ts',
      checkpoints_hook: 'src/modules/agent/hooks/useAgentCheckpoints.ts',
      groups_hook: 'src/modules/agent/hooks/useAgentGroups.ts',
      agent_api_adapter: 'src/api/agent.ts',
      emoji_picker: 'src/modules/agent/components/chat/InputArea.vue',
      voice_recording: 'src/modules/agent/components/chat/InputArea.vue',
      image_preview: 'src/modules/agent/components/chat/ChatMessageList.vue',
    },
  },
  hashMap: {
    getChatHistory: 'hash_getChatHistory_002',
    getWorkflowSteps: 'hash_getWorkflowSteps_003',
    getQuickItems: 'hash_getQuickItems_004',
    startChatStream: 'hash_startChatStream_005',
    getSessionGroups: 'hash_getSessionGroups_006',
    listCheckpoints: 'hash_listCheckpoints_007',
    getCheckpointDetail: 'hash_getCheckpointDetail_008',
    createGroup: 'hash_createGroup_010',
    deleteGroup: 'hash_deleteGroup_009',
    listSessions: 'hash_listThreads_011',
    createSession: 'hash_createThread_012',
    updateSession: 'hash_updateThread_013',
    getGroupSummaries: 'hash_getGroupSummaries_014',
    inputAreaSend: 'hash_inputAreaSend_015',
    persistPanelState: 'hash_panel_persist_001',
    insertMention: 'hash_insertMention_001',
    getMentionCandidates: 'hash_mentionCandidates_001',
    useAgentChat_send: 'hash_hook_chat_send_001',
    useAgentChat_sendToThread: 'hash_hook_chat_send_thread_002',
    useAgentSessions_list: 'hash_hook_sessions_list_003',
    useAgentSessions_create: 'hash_hook_sessions_create_004',
    useAgentSessions_update: 'hash_hook_sessions_update_005',
    useAgentGroups_list: 'hash_hook_groups_list_006',
    useAgentGroups_create: 'hash_hook_groups_create_007',
    useAgentGroups_remove: 'hash_hook_groups_remove_008',
    useAgentGroups_summaries: 'hash_hook_groups_summaries_009',
    tabRegistry: 'web_agent_tab_registry_001',
    chat_history_cache_load: 'hash_chat_cache_load_001',
    chat_history_cache_merge: 'hash_chat_cache_merge_002',
    im_config_cache_getLastReceivedAt: 'hash_imcfg_get_last_001',
    im_config_cache_setLastReceivedAt: 'hash_imcfg_set_last_002',
    agent_store_syncSession: 'hash_agent_store_sync_001',
    agent_store_appendLocalMessage: 'hash_agent_store_append_002',
    contacts_open_profile: 'hash_contacts_open_profile_001',
    contacts_close_profile: 'hash_contacts_close_profile_002',
    contacts_add_member: 'hash_contacts_add_member_003',
    contacts_remove_member: 'hash_contacts_remove_member_004',
    contacts_handle_enter_session: 'hash_contacts_enter_thread_005',
    contacts_handle_profile_enter: 'hash_contacts_profile_enter_006',
    contacts_session_icon: 'hash_contact_avatar_thread_icon_007',
    contacts_avatar_class: 'hash_contact_avatar_class_008',
    contacts_session_label: 'hash_contact_title_display_009',
    chat_session_header_open_tab: 'hash_chat_session_header_open_tab_001',
    chat_session_header_delete: 'hash_chat_session_header_delete_002',
    chat_contacts_load_contacts: 'hash_chat_contacts_load_contacts_001',
    chat_contacts_load_agents: 'hash_chat_contacts_load_agents_002',
    chat_contacts_mention_candidates:
      'hash_chat_contacts_mention_candidates_003',

    chat_sessions_loadSessions: 'web_agent_page_sessions_load_001',
    chat_sessions_enterSession: 'web_agent_page_sessions_enter_002',
    chat_sessions_togglePin: 'web_agent_page_sessions_pin_003',
    chat_sessions_deleteSession: 'web_agent_page_sessions_delete_004',

    chat_contacts_loadContacts: 'web_agent_page_contacts_load_001',
    chat_contacts_enterSession: 'web_agent_page_contacts_enter_002',
    chat_contacts_createSession: 'web_agent_page_contacts_create_003',
    chat_contacts_updateSession: 'web_agent_page_contacts_update_004',

    chat_messages_openSessionAndLoadHistory: 'web_agent_page_messages_open_001',
    chat_messages_ensureImMembership: 'web_agent_page_messages_member_002',
    chat_messages_extractMentions: 'web_agent_page_messages_mention_003',
    chat_messages_sendMessage: 'web_agent_page_messages_send_004',

    chat_daily_render: 'web_agent_page_daily_render_001',
    inputArea_insertEmoji: 'hash_inputArea_emoji_001',
    inputArea_startRecording: 'hash_inputArea_record_001',
    chatMessageList_handleClick: 'hash_chatMsg_click_001',
  },
};
